sudo: required
services:
  - docker

before_install:
  - docker build -t chixdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chixdocker/react-test npm test -- --coverage

after_success:
  - docker build -t chixdocker/multi-client ./client
  - docker build -t chixdocker/multi-nginx ./nginx
  - docker build -t chixdocker/multi-server ./server
  - docker build -t chixdocker/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chixdocker/multi-client
  - docker push chixdocker/multi-nginx
  - docker push chixdocker/multi-server
  - docker push chixdocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-835745771460
  bucket_path: bucket-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
